# pytox.toxav.toxav
from array import array
from types import TracebackType
from typing import Any
from typing import Optional
from typing import TypeVar
import enum
import pytox.common
T = TypeVar("T")
class ApiException(pytox.common.ApiException): ...
class ToxAV_Ptr:
    def __enter__(self: T) -> T: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, exc_traceback: TracebackType | None) -> None: ...
    def __init__(self, tox: Optional[Tox_Ptr] = None) -> None: ...
    def answer(self, friend_number: Tox_Friend_Number, audio_bit_rate: int, video_bit_rate: int) -> bool: ...
    def audio_iterate(self) -> None: ...
    audio_iteration_interval: int
    def audio_send_frame(self, friend_number: Tox_Friend_Number, pcm: array[Any], sample_count: int, channels: int, sampling_rate: int) -> bool: ...
    def audio_set_bit_rate(self, friend_number: Tox_Friend_Number, bit_rate: int) -> bool: ...
    def call(self, friend_number: Tox_Friend_Number, audio_bit_rate: int, video_bit_rate: int) -> bool: ...
    def call_control(self, friend_number: Tox_Friend_Number, control: Toxav_Call_Control) -> bool: ...
    def handle_audio_bit_rate(self, friend_number: int, audio_bit_rate: int) -> None: ...
    def handle_audio_receive_frame(self, friend_number: int, pcm: array[Any], sample_count: int, channels: int, sampling_rate: int) -> None: ...
    def handle_call(self, friend_number: int, audio_enabled: bool, video_enabled: bool) -> None: ...
    def handle_call_state(self, friend_number: int, state: int) -> None: ...
    def handle_video_bit_rate(self, friend_number: int, video_bit_rate: int) -> None: ...
    def handle_video_receive_frame(self, friend_number: int, width: int, height: int, y: bytes, u: bytes, v: bytes, ystride: int, ustride: int, vstride: int) -> None: ...
    def iterate(self) -> None: ...
    iteration_interval: int
    def video_iterate(self) -> None: ...
    video_iteration_interval: int
    def video_send_frame(self, friend_number: Tox_Friend_Number, width: int, height: int, y: bytes, u: bytes, v: bytes) -> bool: ...
    def video_set_bit_rate(self, friend_number: Tox_Friend_Number, bit_rate: int) -> bool: ...
class Toxav_Call_Control(enum.Enum):
    TOXAV_CALL_CONTROL_RESUME = ...
    TOXAV_CALL_CONTROL_PAUSE = ...
    TOXAV_CALL_CONTROL_CANCEL = ...
    TOXAV_CALL_CONTROL_MUTE_AUDIO = ...
    TOXAV_CALL_CONTROL_UNMUTE_AUDIO = ...
    TOXAV_CALL_CONTROL_HIDE_VIDEO = ...
    TOXAV_CALL_CONTROL_SHOW_VIDEO = ...
class Toxav_Err_Answer(enum.Enum):
    TOXAV_ERR_ANSWER_OK = ...
    TOXAV_ERR_ANSWER_SYNC = ...
    TOXAV_ERR_ANSWER_CODEC_INITIALIZATION = ...
    TOXAV_ERR_ANSWER_FRIEND_NOT_FOUND = ...
    TOXAV_ERR_ANSWER_FRIEND_NOT_CALLING = ...
    TOXAV_ERR_ANSWER_INVALID_BIT_RATE = ...
class Toxav_Err_Bit_Rate_Set(enum.Enum):
    TOXAV_ERR_BIT_RATE_SET_OK = ...
    TOXAV_ERR_BIT_RATE_SET_SYNC = ...
    TOXAV_ERR_BIT_RATE_SET_INVALID_BIT_RATE = ...
    TOXAV_ERR_BIT_RATE_SET_FRIEND_NOT_FOUND = ...
    TOXAV_ERR_BIT_RATE_SET_FRIEND_NOT_IN_CALL = ...
class Toxav_Err_Call(enum.Enum):
    TOXAV_ERR_CALL_OK = ...
    TOXAV_ERR_CALL_MALLOC = ...
    TOXAV_ERR_CALL_SYNC = ...
    TOXAV_ERR_CALL_FRIEND_NOT_FOUND = ...
    TOXAV_ERR_CALL_FRIEND_NOT_CONNECTED = ...
    TOXAV_ERR_CALL_FRIEND_ALREADY_IN_CALL = ...
    TOXAV_ERR_CALL_INVALID_BIT_RATE = ...
class Toxav_Err_Call_Control(enum.Enum):
    TOXAV_ERR_CALL_CONTROL_OK = ...
    TOXAV_ERR_CALL_CONTROL_SYNC = ...
    TOXAV_ERR_CALL_CONTROL_FRIEND_NOT_FOUND = ...
    TOXAV_ERR_CALL_CONTROL_FRIEND_NOT_IN_CALL = ...
    TOXAV_ERR_CALL_CONTROL_INVALID_TRANSITION = ...
class Toxav_Err_New(enum.Enum):
    TOXAV_ERR_NEW_OK = ...
    TOXAV_ERR_NEW_NULL = ...
    TOXAV_ERR_NEW_MALLOC = ...
    TOXAV_ERR_NEW_MULTIPLE = ...
class Toxav_Err_Send_Frame(enum.Enum):
    TOXAV_ERR_SEND_FRAME_OK = ...
    TOXAV_ERR_SEND_FRAME_NULL = ...
    TOXAV_ERR_SEND_FRAME_FRIEND_NOT_FOUND = ...
    TOXAV_ERR_SEND_FRAME_FRIEND_NOT_IN_CALL = ...
    TOXAV_ERR_SEND_FRAME_SYNC = ...
    TOXAV_ERR_SEND_FRAME_INVALID = ...
    TOXAV_ERR_SEND_FRAME_PAYLOAD_TYPE_DISABLED = ...
    TOXAV_ERR_SEND_FRAME_RTP_FAILED = ...
