# pytox.toxencryptsave.toxencryptsave
from types import TracebackType
from typing import Optional
from typing import TypeVar
import enum
import pytox.common
T = TypeVar("T")
class ApiException(pytox.common.ApiException): ...
class Tox_Err_Decryption(enum.Enum):
    TOX_ERR_DECRYPTION_OK = ...
    TOX_ERR_DECRYPTION_NULL = ...
    TOX_ERR_DECRYPTION_INVALID_LENGTH = ...
    TOX_ERR_DECRYPTION_BAD_FORMAT = ...
    TOX_ERR_DECRYPTION_KEY_DERIVATION_FAILED = ...
    TOX_ERR_DECRYPTION_FAILED = ...
class Tox_Err_Encryption(enum.Enum):
    TOX_ERR_ENCRYPTION_OK = ...
    TOX_ERR_ENCRYPTION_NULL = ...
    TOX_ERR_ENCRYPTION_KEY_DERIVATION_FAILED = ...
    TOX_ERR_ENCRYPTION_FAILED = ...
class Tox_Err_Get_Salt(enum.Enum):
    TOX_ERR_GET_SALT_OK = ...
    TOX_ERR_GET_SALT_NULL = ...
    TOX_ERR_GET_SALT_BAD_FORMAT = ...
class Tox_Err_Key_Derivation(enum.Enum):
    TOX_ERR_KEY_DERIVATION_OK = ...
    TOX_ERR_KEY_DERIVATION_NULL = ...
    TOX_ERR_KEY_DERIVATION_FAILED = ...
class Tox_Pass_Key_Ptr:
    def __enter__(self: T) -> T: ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, exc_traceback: TracebackType | None) -> None: ...
    def __init__(self, passphrase: bytes, salt: Optional[bytes] = None) -> None: ...
    def decrypt(self, ciphertext: bytes) -> bytes: ...
    def encrypt(self, plaintext: bytes) -> bytes: ...
PASS_ENCRYPTION_EXTRA_LENGTH: int
PASS_KEY_LENGTH: int
PASS_SALT_LENGTH: int
def get_salt(ciphertext: bytes) -> bytes: ...
def is_data_encrypted(data: bytes) -> bool: ...
def pass_decrypt(ciphertext: bytes, passphrase: bytes) -> bytes: ...
def pass_encrypt(plaintext: bytes, passphrase: bytes) -> bytes: ...
